I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/custom/customlabels.rpy", line 21, in script call
    call expression curLocForEvent
  File "game/custom/customlabels.rpy", line 133, in script
    if JacuzziFirstVisit:
  File "game/custom/customlabels.rpy", line 133, in <module>
    if JacuzziFirstVisit:
NameError: name 'JacuzziFirstVisit' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/custom/customlabels.rpy", line 21, in script call
    call expression curLocForEvent
  File "game/custom/customlabels.rpy", line 133, in script
    if JacuzziFirstVisit:
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/custom/customlabels.rpy", line 133, in <module>
    if JacuzziFirstVisit:
NameError: name 'JacuzziFirstVisit' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
ProjectCW 1.0
Wed Jun 14 06:39:21 2023
